{% set version = "0.22" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-contrast
  version: {{ version|replace("-", "_") }}

source:
  fn: contrast_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/contrast_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/contrast/contrast_{{ version }}.tar.gz
  sha256: 9c0b70f007d6f2c06b6ed438ea3d18918ad17365e0fa5c0ab1f70d635b2aff87

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-hmisc
    - r-mass
    - r-geepack
    - r-nlme
    - r-rms
    - r-sandwich

  run:
    - r-base
    - r-hmisc
    - r-mass
    - r-geepack
    - r-nlme
    - r-rms
    - r-sandwich

test:
  commands:
    - $R -e "library('contrast')"  # [not win]
    - "\"%R%\" -e \"library('contrast')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=contrast
  license: GPL-2
  summary: One degree of freedom contrasts for lm, glm, gls, and geese objects.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
