appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: QgfirUpZc3sjd1Xpl64f25ETBA8DENAsVlAe1NxypwCLfaEs+t4SCKCPKpfeNtwmjeWCwZheazP9r/WDWWgttpSP2RcJCVGHGLgiBeDKT51/V0/4SeyCTaiQQooV+HICOJbIXY2WYrhWGqPjEG84CQxj4RlDRt1/MgZhrR8BmRb6dw5krJ6dLLGSmYGGtMaipFqC0gVyXUsw8hNriet6WwyVfF698a5W1d9t7Xht07au2YBYruNHrWGGK5DrM6HuiZAjNXxW9FcvbxTyLjkMCVdOH1jtzu9IRzLvebf38XDqc6mIKJW2cOeAaciwiSET5NdqLAoHov1pOGMgy5DMX0/IeUmqObvMUlCTyFmBkaVE5sBWb7N17aguL10ypnsE7MPGkMqVpJfPrhDHZysWHb9DBu1O/BQqFaTU9MO7KF41jps+S+mq/DTXzNFNrgY96f7mylRg+IKvvAOAF0uKNLChkW0zLLxBwI3Ln8aXOzYsArx03sRhmWjCr2nO/Gxg4VbfLVshO+g4SDbln4y61E5FFrSy16O7qbYY0QFhhcqDY81qMRDWFTTHlZtfUqP5SGVS5cteLg70paQKeWbtIthNyqpPhImdHGnAqb+sy51Z6pE+WQXltJ/LQs7XaDh4cvmigUihA9fGJwYWtk6+o3S1N7Ua9oCQ5qz4irAmXzQ=
