travis:
  secure:
    BINSTAR_TOKEN: ZToFSTmpIokYH/zDEZjVimM8RFUK5xas486cq6gYDK5NZcPNxZrcx5ag0xhvdSWbRULO9utaykmH7WsJAOo36jNikdFkQUGXNiWEwcMKQLO3Nh0nBkMT/CvUggCUIXVEfBMrwG1P4gGvwvuxue9qhvHvRGmeFoE8BNMaeeKYjSYIS7hZSX8WRXLMd/cQAM/lYEeMah2dullEJ9zVN+h17g6SiCRlLFyIocMBf3+Gqt3r3+GS9y4d3XygGPE5tRgCJ48OoavsdSPculqR20xR5JVsLwm9H94wQZ7bdEkZFeJe8clq5z7f82YtptBZ6m56UVzdjZIUWOC7N2Cfno19G14oHQFYwx0g3ylY/B4pq859xbDPnZLvvaF9zdC18l08H0gnHWm4/Zctmw/a6UI1KCI9xCZsEUVeaIO33PLeEL3dHDm42dwsEEAGRGpYe4Ipn7j3zAQCcseZBvHQQAM1ZGsb03Htt346NG2TLSY0Epfmmf/4X3TaTfLvpBGTT8MtN169ByJlvITQA6/KqvJlE8LxTEXfkNIJbxGGL1aBRZIkyOi9aaU3FCpLFtztqBQU9pMK3t+tdA8iaKLTt9CZgUn8LE942mVAWB0ekUZScwod4HgBEBBxkFd/3YdZSllw3gBTDGtFY/BF9WnedhTCFImMvzrlqBvJo6GabDUmKP8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
